
name: RUN UI Automation

# The workflow will run on Monday to Friday at 08:00 AEST (22:00 UTC)
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  endToEnd:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clear Cypress Cache
        run: npx cypress cache clear
      - name: Checkout
      - name: 'End To End Testing - Autobahn Security'
        if: always()
        uses: cypress-io/github-action@v5
        with:
          install-command: yarn
          browser: chrome
          spec: cypress/features/*.feature
      - name: Generate  Report
        if: always()
        run: npm run make-report
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Artifact Report UI Automation
          path: cypress/cucumber-report/
       